In [1]:
#Introduction to Data Science

In [2]:
import numpy as np

In [3]:
## 1. Create a one-dimensional array (vector) with the first 10 natural numbers and display its values.

In [4]:
vector = np.array(range(1, 11), dtype=int)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
## 2. Create a two-dimensional array (matrix) of size 3x3, fill it with zeros and display its values.

In [6]:
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
## 3. Create an array of size 5x5, fill it with random integers in the range from 1 to 10 and display its values.

In [8]:
random_matrix = np.random.randint(1, 11, size=(5, 5))
print(random_matrix)

[[ 5  6  8  3  6]
 [ 1 10  5  8  3]
 [ 8  2  1  9  4]
 [ 9  1 10  1  2]
 [ 7  7  7  6  7]]


In [9]:
## 4. Create an array of size 4x4, fill it with random real numbers in the range from 0 to 1 and display its values.

In [10]:
random_matrix = np.random.randint(0, 2, size=(4, 4))
print(random_matrix)

[[0 0 0 0]
 [0 1 1 0]
 [1 1 1 1]
 [0 0 0 1]]


In [11]:
## 5. Create two one-dimensional arrays of size 5, fill them with random integers in the range from 1 to 10 and perform element-wise addition, subtraction, and multiplication operations on them.

In [12]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
print("Array A:", a)
print("Array B:", b)

Array A: [ 6  3  2  7 10]
Array B: [ 8 10  1  8  1]


In [13]:
print("Result of adding:", a + b)

Result of adding: [14 13  3 15 11]


In [14]:
print("Result of subtraction:", a - b) 

Result of subtraction: [-2 -7  1 -1  9]


In [15]:
print("Result of multiplication:", a * b)

Result of multiplication: [48 30  2 56 10]


In [16]:
## 6. Create two vectors of size 7, fill with arbitrary numbers and find their scalar product.

In [17]:
vector_a = np.random.randint(1, 11, size=7)
vector_b = np.random.randint(1, 11, size=7)
print("Vector A:", vector_a)
print("Vector B:", vector_b)
print("Scalar product:", np.dot(vector_a, vector_b))

Vector A: [4 2 3 3 7 2 8]
Vector B: [10  3 10  1  5  8  1]
Scalar product: 138


In [18]:
## 7. Create two matrices of sizes 2x2 and 2x3, fill them with random integers in the range from 1 to 10 and multiply them together.

In [19]:
matrix_a = np.random.randint(1, 11, size=(2, 2))
matrix_b = np.random.randint(1, 11, size=(2, 3))
print("Matrix A:\n", matrix_a)
print(matrix_a)
print("Matrix B:\n", matrix_b)
print(matrix_b)
result = np.dot(matrix_a, matrix_b)
print("Result of multiplication:\n", result)


Matrix A:
 [[7 7]
 [3 2]]
[[7 7]
 [3 2]]
Matrix B:
 [[8 6 2]
 [6 1 6]]
[[8 6 2]
 [6 1 6]]
Result of multiplication:
 [[98 49 56]
 [36 20 18]]


In [20]:
## 8. Create a matrix of size 3x3, fill it with random integers in the range from 1 to 10 and find its inverse matrix.

In [21]:
matrix = np.random.randint(1, 11, size=(3, 3))
print(matrix)

[[2 5 7]
 [8 8 1]
 [7 9 4]]


In [22]:
inverse_matrix = np.linalg.inv(matrix)
print("Inverse matrix:\n", inverse_matrix)

Inverse matrix:
 [[ 0.6969697   1.3030303  -1.54545455]
 [-0.75757576 -1.24242424  1.63636364]
 [ 0.48484848  0.51515152 -0.72727273]]


In [23]:
## 9. Create a matrix of size 4x4, fill it with random real numbers in the range from 0 to 1 and transpose it.

In [24]:
matrix = np.random.rand(4, 4)
print("Matrix:\n", matrix)
matrix_transpose = matrix.T
print("Result of transpose:\n", matrix_transpose)

Matrix:
 [[0.82626277 0.97501586 0.72130284 0.85675289]
 [0.49038136 0.07000538 0.04403595 0.41338565]
 [0.49790838 0.60882025 0.90670122 0.64622729]
 [0.82391766 0.15254783 0.0273892  0.6117281 ]]
Result of transpose:
 [[0.82626277 0.49038136 0.49790838 0.82391766]
 [0.97501586 0.07000538 0.60882025 0.15254783]
 [0.72130284 0.04403595 0.90670122 0.0273892 ]
 [0.85675289 0.41338565 0.64622729 0.6117281 ]]


In [25]:
## 10. Create a matrix of size 3x4 and a vector of size 4, fill them with random integers in the range from 1 to 10 and multiply the matrix by the vector.

In [26]:
matrix = np.random.randint(1, 11, size=(3, 4))
print("Matrix:\n", matrix)
vector = np.random.randint(1, 11, size=4)
print("Vector:\n", vector)

Matrix:
 [[ 3  6  2  9]
 [ 8  8  3  2]
 [ 8  5  5 10]]
Vector:
 [8 4 2 4]


In [27]:
result = matrix.dot(vector)
print("Result of multiplication:\n", result)

Result of multiplication:
 [ 88 110 134]


In [28]:
## 11. Create a matrix of size 2x3 and a vector of size 3, fill them with random real numbers in the range from 0 to 1 and multiply the matrix by the vector.

In [29]:
matrix = np.random.rand(2, 3)
print("Matrix:\n", matrix)
vector = np.random.rand(3)
print("Vector:\n", vector)

Matrix:
 [[0.63859243 0.82427756 0.29987423]
 [0.34590074 0.60286183 0.51824286]]
Vector:
 [0.33528644 0.45992269 0.3727701 ]


In [30]:
result = matrix.dot(vector)
print("Result of multiplication:\n", result)

Result of multiplication:
 [0.70499947 0.5864311 ]


In [31]:
## 12. Create two matrices of size 2x2, fill them with random integers in the range from 1 to 10 and perform their element-wise multiplication.

In [32]:
matrix_a = np.random.randint(1, 11, size=(2, 2))
print("Matrix A:\n", matrix_a)
matrix_b = np.random.randint(1, 11, size=(2, 2))
print("Matrix B:\n", matrix_b)

Matrix A:
 [[9 5]
 [4 6]]
Matrix B:
 [[10  8]
 [ 7  7]]


In [33]:
result = np.multiply(matrix_a, matrix_b)
print("Result of multiplication:\n", result)

Result of multiplication:
 [[90 40]
 [28 42]]


In [34]:
## 13. Create two matrices of size 2x2, fill them with random integers in the range from 1 to 10 and find their product.

In [35]:
matrix_a = np.random.randint(1, 11, size=(2, 2))
print("Matrix A:\n", matrix_a)
matrix_b = np.random.randint(1, 11, size=(2, 2))
print("Matrix B:\n", matrix_b)

Matrix A:
 [[10  4]
 [ 4  1]]
Matrix B:
 [[10 10]
 [ 5  1]]


In [36]:
product_matrix = matrix_a * matrix_b
print("Product of element-wise multiplication:\n", product_matrix)

Product of element-wise multiplication:
 [[100  40]
 [ 20   1]]


In [37]:
## 14. Create a matrix of size 5x5, fill it with random integers in the range from 1 to 100 and find the sum of the elements of the matrix.

In [38]:
matrix = np.random.randint(1, 101, size=(5, 5))
print("Matrix:\n", matrix)

Matrix:
 [[69  5 38 37 81]
 [76 83 35 96 82]
 [45 56 17  1 35]
 [62 94 84 57  7]
 [38 58 88 42 16]]


In [39]:
result = matrix.sum()
print("Sum of the elements:\n", result)

Sum of the elements:
 1302


In [40]:
## 15. Create two matrices of size 4x4, fill them with random integers in the range from 1 to 10 and find their difference.

In [41]:
matrix_a = np.random.randint(1, 11, size=(4, 4))
print("Matrix A:\n", matrix_a)
matrix_b = np.random.randint(1, 11, size=(4, 4))
print("Matrix B:\n", matrix_b)

Matrix A:
 [[ 6  1  1  3]
 [ 5  9  1  2]
 [ 6  2  2  2]
 [ 5 10  9 10]]
Matrix B:
 [[ 1  7  4  9]
 [ 1  7  1  7]
 [ 9  8  8  5]
 [ 1  8  4 10]]


In [42]:
diff = matrix_a - matrix_b
print("Difference:\n", diff)

Difference:
 [[ 5 -6 -3 -6]
 [ 4  2  0 -5]
 [-3 -6 -6 -3]
 [ 4  2  5  0]]


In [43]:
## 16. Create a matrix of size 3x3, fill it with random real numbers in the range from 0 to 1 and find the column vector that contains the sum of elements of each row of the matrix.

In [44]:
matrix = np.random.rand(3, 3)
print("Matrix:\n", matrix)

Matrix:
 [[0.37801071 0.38921879 0.12225209]
 [0.17906627 0.21014932 0.36685508]
 [0.67189064 0.0351304  0.61852642]]


In [45]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
print("Column vector with the sum of elements of each row:\n", row_sums)

Column vector with the sum of elements of each row:
 [[0.88948159]
 [0.75607067]
 [1.32554747]]


In [46]:
## 17. Create a matrix of size 3x4 with arbitrary integers and create a matrix with the squares of these numbers.

In [47]:
matrix = np.random.randint(1, 11, size=(3,4))
print("Matrix:\n", matrix)
matrix_sq = np.square(matrix)
print("Squared matrix:\n", matrix_sq)

Matrix:
 [[ 9  9  9 10]
 [ 8  6  4  6]
 [ 4  5  1  5]]
Squared matrix:
 [[ 81  81  81 100]
 [ 64  36  16  36]
 [ 16  25   1  25]]


In [48]:
## 18. Create a vector of size 4, fill it with random integers in the range from 1 to 50 and find a vector with the square roots of these numbers.

In [49]:
vector = np.random.randint(1, 51, size=4)
print("Vector:\n", vector)

Vector:
 [16 42 15 40]


In [50]:
vector_sq = np.square(vector)
print("Squared vector:\n", vector_sq)

Squared vector:
 [ 256 1764  225 1600]
