In [20]:
#Introduction to Data Science

In [5]:
import numpy as np

In [19]:
## 1. Create a one-dimensional array (vector) with the first 10 natural numbers and display its values.

In [22]:
vector = np.array(range(1, 11), dtype=int)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
## 2. Create a two-dimensional array (matrix) of size 3x3, fill it with zeros and display its values.

In [19]:
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
## 3. Create an array of size 5x5, fill it with random integers in the range from 1 to 10 and display its values.

In [62]:
random_matrix = np.random.randint(1, 11, size=(5, 5))
print(random_matrix)

[[ 3  7  4  6  1]
 [ 9  7  6 10  2]
 [ 7  2  5  6  7]
 [ 8  8  1 10 10]
 [ 4  4  3  6  2]]


In [ ]:
## 4. Create an array of size 4x4, fill it with random real numbers in the range from 0 to 1 and display its values.

In [71]:
random_matrix = np.random.randint(0, 2, size=(4, 4))
print(random_matrix)

[[1 0 1 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]


In [41]:
## 5. Create two one-dimensional arrays of size 5, fill them with random integers in the range from 1 to 10 and perform element-wise addition, subtraction, and multiplication operations on them.

In [64]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
print("Array A:", a)
print("Array B:", b)

Array A: [ 6 10  9  2  1]
Array B: [ 6 10 10  6  3]


In [66]:
print("Result of adding:", a + b)

Result of adding: [12 20 19  8  4]


In [68]:
print("Result of subtraction:", a - b) 

Result of subtraction: [ 0  0 -1 -4 -2]


In [69]:
print("Result of multiplication:", a * b)

Result of multiplication: [ 36 100  90  12   3]


In [ ]:
## 6. Create two vectors of size 7, fill with arbitrary numbers and find their scalar product.

In [77]:
vector_a = np.random.randint(1, 11, size=7)
vector_b = np.random.randint(1, 11, size=7)
print("Vector A:", vector_a)
print("Vector B:", vector_b)
print("Scalar product:", np.dot(vector_a, vector_b))

Vector A: [6 5 1 3 2 2 8]
Vector B: [9 8 6 1 4 7 6]
Scalar product: 173


In [ ]:
## 7. Create two matrices of sizes 2x2 and 2x3, fill them with random integers in the range from 1 to 10 and multiply them together.

In [96]:
matrix_a = np.random.randint(1, 11, size=(2, 2))
matrix_b = np.random.randint(1, 11, size=(2, 3))
print("Matrix A:\n", matrix_a)
print(matrix_a)
print("Matrix B:\n", matrix_b)
print(matrix_b)
result = np.dot(matrix_a, matrix_b)
print("Result of multiplication:\n", result)


Matrix A:
 [[ 5 10]
 [ 4  6]]
[[ 5 10]
 [ 4  6]]
Matrix B:
 [[ 7 10 10]
 [ 1  7  2]]
[[ 7 10 10]
 [ 1  7  2]]
Result of multiplication:
 [[ 45 120  70]
 [ 34  82  52]]


In [ ]:
## 8. Create a matrix of size 3x3, fill it with random integers in the range from 1 to 10 and find its inverse matrix.

In [97]:
matrix = np.random.randint(1, 11, size=(3, 3))
print(matrix)

[[ 4  8  5]
 [ 3  6  4]
 [ 4 10  3]]


In [99]:
inverse_matrix = np.linalg.inv(matrix)
print("Inverse matrix:\n", inverse_matrix)

Inverse matrix:
 [[ 11.  -13.   -1. ]
 [ -3.5   4.    0.5]
 [ -3.    4.    0. ]]


In [ ]:
## 9. Create a matrix of size 4x4, fill it with random real numbers in the range from 0 to 1 and transpose it.

In [109]:
matrix = np.random.rand(4, 4)
print("Matrix:\n", matrix)
matrix_transpose = matrix.T
print("Result of transpose:\n", matrix_transpose)

Matrix:
 [[0.37388019 0.31910866 0.1865017  0.39030151]
 [0.08262257 0.2450258  0.96275306 0.43359069]
 [0.4933935  0.83029596 0.18708916 0.62804716]
 [0.75169825 0.55654665 0.61579631 0.46142158]]
Result of transpose:
 [[0.37388019 0.08262257 0.4933935  0.75169825]
 [0.31910866 0.2450258  0.83029596 0.55654665]
 [0.1865017  0.96275306 0.18708916 0.61579631]
 [0.39030151 0.43359069 0.62804716 0.46142158]]


In [ ]:
## 10. Create a matrix of size 3x4 and a vector of size 4, fill them with random integers in the range from 1 to 10 and multiply the matrix by the vector.

In [110]:
matrix = np.random.randint(1, 11, size=(3, 4))
print("Matrix:\n", matrix)
vector = np.random.randint(1, 11, size=4)
print("Vector:\n", vector)

Matrix:
 [[7 8 8 8]
 [1 8 9 7]
 [4 8 7 8]]
Vector:
 [7 8 6 7]


In [111]:
result = matrix.dot(vector)
print("Result of multiplication:\n", result)

Result of multiplication:
 [217 174 190]


In [ ]:
## 11. Create a matrix of size 2x3 and a vector of size 3, fill them with random real numbers in the range from 0 to 1 and multiply the matrix by the vector.

In [6]:
matrix = np.random.rand(2, 3)
print("Matrix:\n", matrix)
vector = np.random.rand(3)
print("Vector:\n", vector)

Matrix:
 [[0.09514991 0.55842156 0.52575788]
 [0.91018854 0.59613404 0.18992708]]
Vector:
 [0.38734147 0.19123843 0.88745237]


In [7]:
result = matrix.dot(vector)
print("Result of multiplication:\n", result)

Result of multiplication:
 [0.61023225 0.63510875]


In [ ]:
## 12. Create two matrices of size 2x2, fill them with random integers in the range from 1 to 10 and perform their element-wise multiplication.

In [8]:
matrix_a = np.random.randint(1, 11, size=(2, 2))
print("Matrix A:\n", matrix_a)
matrix_b = np.random.randint(1, 11, size=(2, 2))
print("Matrix B:\n", matrix_b)

Matrix A:
 [[ 7  8]
 [10  7]]
Matrix B:
 [[10  6]
 [ 4 10]]


In [9]:
result = np.multiply(matrix_a, matrix_b)
print("Result of multiplication:\n", result)

Result of multiplication:
 [[70 48]
 [40 70]]


In [ ]:
## 13. Create two matrices of size 2x2, fill them with random integers in the range from 1 to 10 and find their product.

In [11]:
matrix_a = np.random.randint(1, 11, size=(2, 2))
print("Matrix A:\n", matrix_a)
matrix_b = np.random.randint(1, 11, size=(2, 2))
print("Matrix B:\n", matrix_b)

Matrix A:
 [[3 6]
 [8 7]]
Matrix B:
 [[4 2]
 [7 6]]


In [13]:
product_matrix = matrix_a * matrix_b
print("Product of element-wise multiplication:\n", product_matrix)

Product of element-wise multiplication:
 [[12 12]
 [56 42]]


In [ ]:
## 14. Create a matrix of size 5x5, fill it with random integers in the range from 1 to 100 and find the sum of the elements of the matrix.

In [14]:
matrix = np.random.randint(1, 101, size=(5, 5))
print("Matrix:\n", matrix)

Matrix:
 [[13 72 11 40 27]
 [49 67 85 96 14]
 [55 35 55 88 95]
 [78 41  2  1 40]
 [91  9 27 89 63]]


In [15]:
result = matrix.sum()
print("Sum of the elements:\n", result)

Sum of the elements:
 1243


In [ ]:
## 15. Create two matrices of size 4x4, fill them with random integers in the range from 1 to 10 and find their difference.

In [16]:
matrix_a = np.random.randint(1, 11, size=(4, 4))
print("Matrix A:\n", matrix_a)
matrix_b = np.random.randint(1, 11, size=(4, 4))
print("Matrix B:\n", matrix_b)

Matrix A:
 [[ 1  1 10  3]
 [ 6  4  9  3]
 [ 9 10  1  7]
 [ 7 10  5  8]]
Matrix B:
 [[3 9 3 4]
 [2 7 7 4]
 [2 9 1 7]
 [3 2 1 3]]


In [17]:
diff = matrix_a - matrix_b
print("Difference:\n", diff)

Difference:
 [[-2 -8  7 -1]
 [ 4 -3  2 -1]
 [ 7  1  0  0]
 [ 4  8  4  5]]


In [ ]:
## 16. Create a matrix of size 3x3, fill it with random real numbers in the range from 0 to 1 and find the column vector that contains the sum of elements of each row of the matrix.

In [18]:
matrix = np.random.rand(3, 3)
print("Matrix:\n", matrix)

Matrix:
 [[0.63921429 0.39770882 0.70884814]
 [0.47627109 0.1033708  0.65667002]
 [0.58333082 0.98046037 0.62786756]]


In [19]:
row_sums = np.sum(matrix, axis=1)
print("Sum of elements of each row:\n", row_sums)

Sum of elements of each row:
 [1.74577124 1.23631191 2.19165875]


In [ ]:
## 17. Create a matrix of size 3x4 with arbitrary integers and create a matrix with the squares of these numbers.

In [22]:
matrix = np.random.randint(1, 11, size=(3,4))
print("Matrix:\n", matrix)
matrix_sq = np.square(matrix)
print("Squared matrix:\n", matrix_sq)

Matrix:
 [[ 5  3  1  5]
 [10  7  5  9]
 [ 5  7 10  2]]
Squared matrix:
 [[ 25   9   1  25]
 [100  49  25  81]
 [ 25  49 100   4]]


In [ ]:
## 18. Create a vector of size 4, fill it with random integers in the range from 1 to 50 and find a vector with the square roots of these numbers.

In [28]:
vector = np.random.randint(1, 51, size=4)
print("Vector:\n", vector)

Vector:
 [ 7  6 29 49]


In [26]:
vector_sq = np.square(vector)
print("Squared vector:\n", vector_sq)

Squared vector:
 [ 576    4 1156  169]
